In [42]:
import json
import pandas as pd

import ast

In [43]:
filename_games='.\Datasets\steam_games\output_steam_games.json'
filename_reviews='.\\Datasets\\user_reviews\\australian_user_reviews.json'
filename_items='.\\Datasets\\users_items\\australian_users_items.json'

data=[]
#Extraemos los datos de los jason y los convertimos de DataFrames
with open(filename_games, "r", encoding="utf8") as json_file:
    for line in json_file:
        json_data = json.loads(line)
        data.append(json_data)

# Crear un DataFrame con los datos extraídos
df_games = pd.DataFrame(data)

# Leer el contenido del archivo, en este caso el archivo json esta mal estructurado por lo que utilizo ast
lista=[]
with open('.\\Datasets\\user_reviews\\australian_user_reviews.json',encoding="utf-8") as file:
    for line in file.readlines():
        lista.append(ast.literal_eval(line))

# Crear un DataFrame con los datos extraídos
df_reviews=pd.DataFrame(lista)


# Leer el contenido del archivo, en este caso el archivo json esta mal estructurado por lo que utilizo ast
lista2=[]
with open('.\\Datasets\\users_items\\australian_users_items.json',encoding="utf-8") as file:
    for line in file.readlines():
        lista2.append(ast.literal_eval(line))

# Crear un DataFrame con los datos extraídos
df_items=pd.DataFrame(lista2)

In [44]:
df_games.tail(10)

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
120435,Retro Army Limited,"[Action, Adventure, Indie]",The spy who shot me™,The spy who shot me™,http://store.steampowered.com/app/771810/The_s...,2018-10-01,"[Action, Adventure, Indie]",http://steamcommunity.com/app/771810/reviews/?...,"[Single-player, Captions available]",NaN,False,771810,Retro Army Limited
120436,OrtiGames/OrtiSoft,"[Casual, Indie]",Raining blocks,Raining blocks,http://store.steampowered.com/app/767590/Raini...,2018-01-04,"[Indie, Casual]",http://steamcommunity.com/app/767590/reviews/?...,"[Single-player, Shared/Split Screen, Steam Ach...",0.99,False,767590,"Oscar Ortigueira López,OrtiGames/OrtiSoft"
120437,INGAME,"[Indie, RPG]",Bravium,Bravium,http://store.steampowered.com/app/747320/Bravium/,2018-01-04,"[Indie, RPG, Puzzle, Tower Defense]",http://steamcommunity.com/app/747320/reviews/?...,"[Single-player, Steam Achievements, Steam Lead...",14.99,False,747320,INGAME
120438,Riviysky,"[Casual, Indie]",BAE 2,BAE 2,http://store.steampowered.com/app/769330/BAE_2/,2018-01-04,"[Indie, Casual]",http://steamcommunity.com/app/769330/reviews/?...,[Single-player],NaN,False,769330,Riviysky
120439,Bidoniera Games,"[Action, Adventure, Casual, Indie]",Kebab it Up!,Kebab it Up!,http://store.steampowered.com/app/745400/Kebab...,2018-01-04,"[Action, Indie, Casual, Violent, Adventure]",http://steamcommunity.com/app/745400/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",1.99,False,745400,Bidoniera Games
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,False,773640,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns"
120444,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,NaN,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN

In [45]:
df_reviews

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."
...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la..."
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l..."
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',..."
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l..."
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',..."

In [46]:
df_items.head(30)

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
5,MinxIsBetterThanPotatoes,371,76561198004744620,http://steamcommunity.com/id/MinxIsBetterThanP...,"[{'item_id': '50', 'item_name': 'Half-Life: Op..."
6,NitemarePK,304,76561197990951820,http://steamcommunity.com/id/NitemarePK,"[{'item_id': '240', 'item_name': 'Counter-Stri..."
7,themanwich,258,76561198035296505,http://steamcommunity.com/id/themanwich,"[{'item_id': '220', 'item_name': 'Half-Life 2'..."
8,maplemage,629,76561198026584251,http://steamcommunity.com/id/maplemage,"[{'item_id': '240', 'item_name': 'Counter-Stri..."
9,Wackky,0,76561198039117046,http://steamcommunity.com/id/Wackky,[]
10,corrupted_soul,115,76561198007659921,http://steamcommunity.com/id/corrupted_soul,"[{'item_id': '4000', 'item_name': 'Garry's Mod..."
11,76561198079601835,0,76561198079601835,http://steamcommunity.com/profiles/76561198079...,[]
12,jorellpogi,71,76561198103696236,http://steamcommunity.com/id/jorellpogi,"[{'item_id': '240', 'item_name': 'Counter-Stri..."
13,cadmusthreepointoh,253,76561198027078629,http://steamcommunity.com/id/cadmusthreepointoh,"[{'item_id': '3920', 'item_name': 'Sid Meier's..."
14,76561198064823719,55,76561198064823719,http://steamcommunity.com/profiles/76561198064...,"[{'item_id': '220', 'item_name': 'Half-Life 2'..."
15,MeaTCompany,14,76561198071532177,http://steamcommunity.com/id/MeaTCompany,"[{'item_id': '240', 'item_name': 'Counter-Stri..."
16,76561198089393905,103,76561198089393905,http://steamcommunity.com/profiles/76561198089...,"[{'item_id': '4000', 'item_name': 'Garry's Mod..."
17,76561198156664158,59,76561198156664158,http://steamcommunity.com/profiles/76561198156...,"[{'item_id': '4000', 'item_name': 'Garry's Mod..."
18,76561198077246154,174,76561198077246154,http://steamcommunity.com/profiles/76561198077...,"[{'item_id': '4000', 'item_name': 'Garry's Mod..."
19,76561198070234207,33,76561198070234207,http://steamcommunity.com/profiles/76561198070...,"[{'item_id': '43110', 'item_name': 'Metro 2033..."
20,WeiEDKrSat,28,76561198041660154,http://steamcommunity.com/id/WeiEDKrSat,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
21,thequeenpanda,524,76561198010803705,http://steamcommunity.com/id/thequeenpanda,"[{'item_id': '300', 'item_name': 'Day of Defea..."
22,death-hunter,121,76561198018556265,http://steamcommunity.com/id/death-hunter,"[{'item_id': '300', 'item_name': 'Day of Defea..."
23,turneddreamsintoanempire,96,76561198122837537,http://steamcommunity.com/id/turneddreamsintoa...,"[{'item_id': '15100', 'item_name': 'Assassin's..."
24,DJKamBer,152,76561198026039330,http://steamcommunity.com/id/DJKamBer,"[{'item_id': '4000', 'item_name': 'Garry's Mod..."
25,76561198030389591,12,76561198030389591,http://steamcommunity.com/profiles/76561198030...,"[{'item_id': '205790', 'item_name': 'Dota 2 Te..."
26,Rainbow-Dashie,59,76561198087659130,http://steamcommunity.com/id/Rainbow-Dashie,"[{'item_id': '4000', 'item_name': 'Garry's Mod..."
27,btuty8trgt,99,76561198054746068,http://steamcommunity.com/id/btuty8trgt,"[{'item_id': '4000', 'item_name': 'Garry's Mod..."
28,76561198043472122,88,76561198043472122,http://steamcommunity.com/profiles/76561198043...,"[{'item_id': '240', 'item_name': 'Counter-Stri..."
29,MarbleShrine,185,76561198062570934,http://steamcommunity.com/id/MarbleShrine,"[{'item_id': '3910', 'item_name': 'Sid Meier's..."

Realizaremos la limpieza de datos de los tres Data Frames generados

In [47]:
#Vizualiso la informacion del data frame
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120445 entries, 0 to 120444
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24083 non-null  object
 1   genres        28852 non-null  object
 2   app_name      32133 non-null  object
 3   title         30085 non-null  object
 4   url           32135 non-null  object
 5   release_date  30068 non-null  object
 6   tags          31972 non-null  object
 7   reviews_url   32133 non-null  object
 8   specs         31465 non-null  object
 9   price         30758 non-null  object
 10  early_access  32135 non-null  object
 11  id            32133 non-null  object
 12  developer     28836 non-null  object
dtypes: object(13)
memory usage: 11.9+ MB

In [48]:
#Eliminar las filas que tienen solo nulo en todas sus columnas
steam_games = df_games.dropna(how='all')
steam_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32135 entries, 88310 to 120444
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24083 non-null  object
 1   genres        28852 non-null  object
 2   app_name      32133 non-null  object
 3   title         30085 non-null  object
 4   url           32135 non-null  object
 5   release_date  30068 non-null  object
 6   tags          31972 non-null  object
 7   reviews_url   32133 non-null  object
 8   specs         31465 non-null  object
 9   price         30758 non-null  object
 10  early_access  32135 non-null  object
 11  id            32133 non-null  object
 12  developer     28836 non-null  object
dtypes: object(13)
memory usage: 3.4+ MB

In [49]:
#Cuento la cantidad de Nulos
steam_games.isnull().sum()

publisher       8052
genres          3283
app_name           2
title           2050
url                0
release_date    2067
tags             163
reviews_url        2
specs            670
price           1377
early_access       0
id                 2
developer       3299
dtype: int64

Procedo a revisar la columnas que tienen 2 nulos

In [50]:
steam_games[steam_games['app_name'].isnull()]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
88384,NaN,NaN,NaN,NaN,http://store.steampowered.com/,NaN,NaN,NaN,NaN,19.99,False,NaN,NaN
90890,NaN,"[Action, Indie]",NaN,NaN,http://store.steampowered.com/app/317160/_/,2014-08-26,"[Action, Indie]",http://steamcommunity.com/app/317160/reviews/?...,"[Single-player, Game demo]",NaN,False,317160,NaN

In [51]:
steam_games[steam_games['id'].isnull()]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
88384,NaN,NaN,NaN,NaN,http://store.steampowered.com/,NaN,NaN,NaN,NaN,19.99,False,NaN,NaN
119271,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",NaN,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,NaN,"Rocksteady Studios,Feral Interactive (Mac)"

In [52]:
steam_games[steam_games['reviews_url'].isnull()]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
88384,NaN,NaN,NaN,NaN,http://store.steampowered.com/,NaN,NaN,NaN,NaN,19.99,False,NaN,NaN
119271,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",NaN,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,NaN,"Rocksteady Studios,Feral Interactive (Mac)"

Valido que las tres filas no cuentan con informacion relevante por lo que procedo a borrarlas, adicionalmente convierto el tipo valor de id en enteros

In [53]:
steam_games.dropna(subset=['id'],inplace=True)
steam_games.dropna(subset=['app_name'], inplace=True)
steam_games['id'] = steam_games['id'].astype('int')
steam_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32132 entries, 88310 to 120444
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24082 non-null  object
 1   genres        28850 non-null  object
 2   app_name      32132 non-null  object
 3   title         30084 non-null  object
 4   url           32132 non-null  object
 5   release_date  30066 non-null  object
 6   tags          31970 non-null  object
 7   reviews_url   32132 non-null  object
 8   specs         31463 non-null  object
 9   price         30756 non-null  object
 10  early_access  32132 non-null  object
 11  id            32132 non-null  int32
 12  developer     28835 non-null  object
dtypes: int32(1), object(12)
memory usage: 3.3+ MB

C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\2283975330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games.dropna(subset=['id'],inplace=True)
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\2283975330.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games.dropna(subset=['app_name'], inplace=True)
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\2283975330.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games['id'] = steam_games['id'].astype('int')

Revisando los datos me doy cuenta que la columna Publisher y Developer son parecidos por lo que tomo los valores de Publisher para llenar la informacion faltante en Developer y viceversa

In [54]:
steam_games['publisher'].fillna(steam_games['developer'],inplace=True)
steam_games['developer'].fillna(steam_games['publisher'],inplace=True)
steam_games.isnull().sum()

C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\2581174530.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  steam_games['publisher'].fillna(steam_games['developer'],inplace=True)
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\2581174530.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games['publisher'].fillna(steam_games['developer'],inplace=True)
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\2581174530.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  steam_games['developer'].fillna(steam_games['publisher'],inplace=True)
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\2581174530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games['developer'].fillna(steam_games['publisher'],inplace=True)

publisher       3232
genres          3282
app_name           0
title           2048
url                0
release_date    2066
tags             162
reviews_url        0
specs            669
price           1376
early_access       0
id                 0
developer       3232
dtype: int64

Se procede a transformar y limpiar las columnas segun los requerimientos de la API

In [55]:
# Se observan las cantidades de registros por cada fecha
steam_games['release_date'].value_counts()

release_date
2012-10-16    100
2017-08-31     92
2017-09-26     89
2017-06-21     82
2017-07-25     78
             ...
1988-04-16      1
2013-08-24      1
2011-05-07      1
2010-08-21      1
2018-10-01      1
Name: count, Length: 3582, dtype: int64

In [56]:
# Convertir la columna 'release_date' al tipo datetime
steam_games['release_date'] = pd.to_datetime(steam_games['release_date'], errors='coerce')
# Extraer el año y crear una nueva columna 'Año'
steam_games['año_lanzamiento'] = steam_games['release_date'].dt.year   
steam_games['año_lanzamiento'] = steam_games['año_lanzamiento'].astype('Int64')
# elimina la columna 'release_date'
steam_games = steam_games.drop('release_date', axis=1)

# Mostrar el dataframe resultante
steam_games.head()

C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\671286899.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games['release_date'] = pd.to_datetime(steam_games['release_date'], errors='coerce')
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\671286899.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games['año_lanzamiento'] = steam_games['release_date'].dt.year
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\671286899.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_games['año_lanzamiento'] = steam_games['año_lanzamiento'].astype('Int64')

,publisher,genres,app_name,title,url,tags,reviews_url,specs,price,early_access,id,developer,año_lanzamiento
88310,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
88311,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free To Play,False,643980,Secret Level SRL,2018
88312,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free to Play,False,670290,Poolians.com,2017
88313,彼岸领域,"[Action, Adventure, Casual]",弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,彼岸领域,2017
88314,NaN,NaN,Log Challenge,NaN,http://store.steampowered.com/app/773570/Log_C...,"[Action, Indie, Casual, Sports]",http://steamcommunity.com/app/773570/reviews/?...,"[Single-player, Full controller support, HTC V...",2.99,False,773570,NaN,<NA>

In [57]:
# Suponiendo que df es tu DataFrame y 'precio' es la columna de precios
# Reemplazar valores de texto por 0
steam_games['price'] = pd.to_numeric(steam_games['price'], errors='coerce')
steam_games['price'] = steam_games['price'].replace(['Free to Use', 'Free to Play'], 0)

# Imputar valores nulos como 0
steam_games['price'] = steam_games['price'].fillna(0)

# Convertir a tipo numérico (si no lo ha hecho automáticamente)
steam_games['price'] = pd.to_numeric(steam_games['price'])

Se tiene que separar los generos ubicados en listas por lo que se copiaran las filas segun los generos que haya en cada lista y luego se borraran las filas que tengan generos vacios

In [58]:
steam_games = steam_games.explode('genres')
steam_games = steam_games.dropna(subset=['genres'])
steam_games.head(20)

,publisher,genres,app_name,title,url,tags,reviews_url,specs,price,early_access,id,developer,año_lanzamiento
88310,Kotoshiro,Action,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
88310,Kotoshiro,Casual,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
88310,Kotoshiro,Indie,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
88310,Kotoshiro,Simulation,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
88310,Kotoshiro,Strategy,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
88311,"Making Fun, Inc.",Free to Play,Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,643980,Secret Level SRL,2018
88311,"Making Fun, Inc.",Indie,Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,643980,Secret Level SRL,2018
88311,"Making Fun, Inc.",RPG,Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,643980,Secret Level SRL,2018
88311,"Making Fun, Inc.",Strategy,Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,643980,Secret Level SRL,2018
88312,Poolians.com,Casual,Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,670290,Poolians.com,2017
88312,Poolians.com,Free to Play,Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,670290,Poolians.com,2017
88312,Poolians.com,Indie,Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,670290,Poolians.com,2017
88312,Poolians.com,Simulation,Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,670290,Poolians.com,2017
88312,Poolians.com,Sports,Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,670290,Poolians.com,2017
88313,彼岸领域,Action,弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,彼岸领域,2017
88313,彼岸领域,Adventure,弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,彼岸领域,2017
88313,彼岸领域,Casual,弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,彼岸领域,2017
88315,Trickjump Games Ltd,Action,Battle Royale Trainer,Battle Royale Trainer,http://store.steampowered.com/app/772540/Battl...,"[Action, Adventure, Simulation, FPS, Shooter, ...",http://steamcommunity.com/app/772540/reviews/?...,"[Single-player, Steam Achievements]",3.99,False,772540,Trickjump Games Ltd,2018
88315,Trickjump Games Ltd,Adventure,Battle Royale Trainer,Battle Royale Trainer,http://store.steampowered.com/app/772540/Battl...,"[Action, Adventure, Simulation, FPS, Shooter, ...",http://steamcommunity.com/app/772540/reviews/?...,"[Single-player, Steam Achievements]",3.99,False,772540,Trickjump Games Ltd,2018
88315,Trickjump Games Ltd,Simulation,Battle Royale Trainer,Battle Royale Trainer,http://store.steampowered.com/app/772540/Battl...,"[Action, Adventure, Simulation, FPS, Shooter, ...",http://steamcommunity.com/app/772540/reviews/?...,"[Single-player, Steam Achievements]",3.99,False,772540,Trickjump Games Ltd,2018

In [59]:
steam_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71550 entries, 88310 to 120443
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   publisher        71318 non-null  object
 1   genres           71550 non-null  object
 2   app_name         71550 non-null  object
 3   title            71550 non-null  object
 4   url              71550 non-null  object
 5   tags             71504 non-null  object
 6   reviews_url      71550 non-null  object
 7   specs            70993 non-null  object
 8   price            71550 non-null  float64
 9   early_access     71550 non-null  object
 10  id               71550 non-null  int32
 11  developer        71318 non-null  object
 12  año_lanzamiento  70700 non-null  Int64
dtypes: Int64(1), float64(1), int32(1), object(10)
memory usage: 7.4+ MB

In [60]:
#Eliminar columnas que no se utilizaran
steam_games = steam_games.drop(['tags', 'specs', 'url', 'reviews_url'], axis=1)
steam_games.columns

Index(['publisher', 'genres', 'app_name', 'title', 'price', 'early_access',
       'id', 'developer', 'año_lanzamiento'],
      dtype='object')

In [61]:
#le asigno el string 'Sin Datos' a las columnas publiser y developer que no cuentan con informacion
steam_games['publisher'].fillna(value='Sin datos', inplace=True)
steam_games['developer'].fillna(value='Sin datos', inplace=True)
steam_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71550 entries, 88310 to 120443
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   publisher        71550 non-null  object
 1   genres           71550 non-null  object
 2   app_name         71550 non-null  object
 3   title            71550 non-null  object
 4   price            71550 non-null  float64
 5   early_access     71550 non-null  object
 6   id               71550 non-null  int32
 7   developer        71550 non-null  object
 8   año_lanzamiento  70700 non-null  Int64
dtypes: Int64(1), float64(1), int32(1), object(6)
memory usage: 5.3+ MB

C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\359331765.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  steam_games['publisher'].fillna(value='Sin datos', inplace=True)
C:\Users\Manuel\AppData\Local\Temp\ipykernel_28896\359331765.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  steam_games['developer'].fillna(value='Sin datos', inplace=True)

In [62]:
#Subo el archivo corregido
archivo_limpio = 'Datasets_limpio/steam_games.csv'
steam_games.to_csv(archivo_limpio, index=False, encoding='utf-8')

Ahora procesare la data de reviews

In [63]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25799 entries, 0 to 25798
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   25799 non-null  object
 1   user_url  25799 non-null  object
 2   reviews   25799 non-null  object
dtypes: object(3)
memory usage: 604.8+ KB

In [64]:
#Se borran los duplicados por medio de la columna"user_id"
df_reviews_sin_duplicados = df_reviews.drop_duplicates(subset=['user_id'])
df_reviews_sin_duplicados

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."
...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la..."
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l..."
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',..."
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l..."
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',..."

In [65]:
# Se transforma a columnas cada elemento de las listas
df_reviews2 = pd.json_normalize(df_reviews['reviews'])
df_reviews2

,0,1,2,3,4,5,6,7,8,9
0,"{'funny': '', 'posted': 'Posted November 5, 20...","{'funny': '', 'posted': 'Posted July 15, 2011....","{'funny': '', 'posted': 'Posted April 21, 2011...",None,None,None,None,None,None,None
1,"{'funny': '', 'posted': 'Posted June 24, 2014....","{'funny': '', 'posted': 'Posted September 8, 2...","{'funny': '', 'posted': 'Posted November 29, 2...",None,None,None,None,None,None,None
2,"{'funny': '', 'posted': 'Posted February 3.', ...","{'funny': '', 'posted': 'Posted December 4, 20...","{'funny': '', 'posted': 'Posted November 3, 20...","{'funny': '', 'posted': 'Posted October 15, 20...","{'funny': '', 'posted': 'Posted October 15, 20...","{'funny': '', 'posted': 'Posted October 15, 20...",None,None,None,None
3,"{'funny': '', 'posted': 'Posted October 14, 20...","{'funny': '', 'posted': 'Posted July 28, 2012....","{'funny': '', 'posted': 'Posted June 2, 2012.'...","{'funny': '', 'posted': 'Posted June 29, 2014....","{'funny': '', 'posted': 'Posted November 22, 2...","{'funny': '', 'posted': 'Posted February 23, 2...",None,None,None,None
4,"{'funny': '3 people found this review funny', ...","{'funny': '1 person found this review funny', ...","{'funny': '2 people found this review funny', ...","{'funny': '', 'posted': 'Posted July 11, 2013....",None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
25794,"{'funny': '', 'posted': 'Posted May 31.', 'las...",None,None,None,None,None,None,None,None,None
25795,"{'funny': '', 'posted': 'Posted June 17.', 'la...",None,None,None,None,None,None,None,None,None
25796,"{'funny': '1 person found this review funny', ...",None,None,None,None,None,None,None,None,None
25797,"{'funny': '', 'posted': 'Posted July 21.', 'la...","{'funny': '', 'posted': 'Posted July 10.', 'la...","{'funny': '', 'posted': 'Posted July 10.', 'la...","{'funny': '', 'posted': 'Posted July 8.', 'las...",None,None,None,None,None,None
25798,"{'funny': '1 person found this review funny', ...","{'funny': '', 'posted': 'Posted July 20.', 'la...","{'funny': '', 'posted': 'Posted July 2.', 'las...",None,None,None,None,None,None,None

In [66]:
# Se agrega el 'user_id' y 'user_url' a las columnas separadas 
df_reviews2 = pd.concat([df_reviews[['user_id', 'user_url']], df_reviews2], axis=1)
df_reviews2.head()

,user_id,user_url,0,1,2,3,4,5,6,7,8,9
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'funny': '', 'posted': 'Posted November 5, 20...","{'funny': '', 'posted': 'Posted July 15, 2011....","{'funny': '', 'posted': 'Posted April 21, 2011...",None,None,None,None,None,None,None
1,js41637,http://steamcommunity.com/id/js41637,"{'funny': '', 'posted': 'Posted June 24, 2014....","{'funny': '', 'posted': 'Posted September 8, 2...","{'funny': '', 'posted': 'Posted November 29, 2...",None,None,None,None,None,None,None
2,evcentric,http://steamcommunity.com/id/evcentric,"{'funny': '', 'posted': 'Posted February 3.', ...","{'funny': '', 'posted': 'Posted December 4, 20...","{'funny': '', 'posted': 'Posted November 3, 20...","{'funny': '', 'posted': 'Posted October 15, 20...","{'funny': '', 'posted': 'Posted October 15, 20...","{'funny': '', 'posted': 'Posted October 15, 20...",None,None,None,None
3,doctr,http://steamcommunity.com/id/doctr,"{'funny': '', 'posted': 'Posted October 14, 20...","{'funny': '', 'posted': 'Posted July 28, 2012....","{'funny': '', 'posted': 'Posted June 2, 2012.'...","{'funny': '', 'posted': 'Posted June 29, 2014....","{'funny': '', 'posted': 'Posted November 22, 2...","{'funny': '', 'posted': 'Posted February 23, 2...",None,None,None,None
4,maplemage,http://steamcommunity.com/id/maplemage,"{'funny': '3 people found this review funny', ...","{'funny': '1 person found this review funny', ...","{'funny': '2 people found this review funny', ...","{'funny': '', 'posted': 'Posted July 11, 2013....",None,None,None,None,None,None

In [67]:
# Se utiliza pd.melt para transformar las columnas en filas conservando el 'user_id' y 'user_url'
df_reviews2 = pd.melt(df_reviews2, id_vars=['user_id', 'user_url'], 
                       value_vars=list(range(9)),
                       value_name='reviews')

In [68]:
df_reviews

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."
...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la..."
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l..."
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',..."
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l..."
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',..."

In [69]:
df_reviews2 = df_reviews2.dropna()

In [70]:
df_reviews2

,user_id,user_url,variable,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,0,"{'funny': '', 'posted': 'Posted November 5, 20..."
1,js41637,http://steamcommunity.com/id/js41637,0,"{'funny': '', 'posted': 'Posted June 24, 2014...."
2,evcentric,http://steamcommunity.com/id/evcentric,0,"{'funny': '', 'posted': 'Posted February 3.', ..."
3,doctr,http://steamcommunity.com/id/doctr,0,"{'funny': '', 'posted': 'Posted October 14, 20..."
4,maplemage,http://steamcommunity.com/id/maplemage,0,"{'funny': '3 people found this review funny', ..."
...,...,...,...,...
231919,SKELETRONPRIMEISOP,http://steamcommunity.com/id/SKELETRONPRIMEISOP,8,"{'funny': '', 'posted': 'Posted August 15, 201..."
231921,76561198141079508,http://steamcommunity.com/profiles/76561198141...,8,"{'funny': '', 'posted': 'Posted August 2, 2014..."
232047,ShadowYT100,http://steamcommunity.com/id/ShadowYT100,8,"{'funny': '', 'posted': 'Posted July 31, 2015...."
232127,bestcustomurlevermade,http://steamcommunity.com/id/bestcustomurlever...,8,"{'funny': '', 'posted': 'Posted December 20, 2..."
232129,76561198209894493,http://steamcommunity.com/profiles/76561198209...,8,"{'funny': '', 'posted': 'Posted February 3.', ..."

:

In [29]:
# Separo por columnas cada una de las claves de 'reviews'
df_reviews = df_reviews2['reviews'].apply(pd.Series, dtype='object')
df_reviews = df_reviews.add_prefix('reviews_')
df_reviews.head()

,reviews_funny,reviews_posted,reviews_last_edited,reviews_item_id,reviews_helpful,reviews_recommend,reviews_review
0,,"Posted November 5, 2011.",,1250,No ratings yet,True,Simple yet with great replayability. In my opi...
1,,"Posted June 24, 2014.",,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...
2,,Posted February 3.,,248820,No ratings yet,True,A suitably punishing roguelike platformer. Wi...
3,,"Posted October 14, 2013.",,250320,2 of 2 people (100%) found this review helpful,True,This game... is so fun. The fight sequences ha...
4,3 people found this review funny,"Posted April 15, 2014.",,211420,35 of 43 people (81%) found this review helpful,True,Git gud

In [30]:
# Vuelvo a unir 'user_id' y 'user_url' con el data frame
df_reviews = pd.concat([df_reviews2[['user_id', 'user_url']], df_reviews], axis=1)
df_reviews.head()

,user_id,user_url,reviews_funny,reviews_posted,reviews_last_edited,reviews_item_id,reviews_helpful,reviews_recommend,reviews_review
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,,"Posted November 5, 2011.",,1250,No ratings yet,True,Simple yet with great replayability. In my opi...
1,js41637,http://steamcommunity.com/id/js41637,,"Posted June 24, 2014.",,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...
2,evcentric,http://steamcommunity.com/id/evcentric,,Posted February 3.,,248820,No ratings yet,True,A suitably punishing roguelike platformer. Wi...
3,doctr,http://steamcommunity.com/id/doctr,,"Posted October 14, 2013.",,250320,2 of 2 people (100%) found this review helpful,True,This game... is so fun. The fight sequences ha...
4,maplemage,http://steamcommunity.com/id/maplemage,3 people found this review funny,"Posted April 15, 2014.",,211420,35 of 43 people (81%) found this review helpful,True,Git gud

In [31]:
#Remplazo los valores vacios con nulos
df_reviews.replace('', None, inplace=True)
df_reviews.head()

,user_id,user_url,reviews_funny,reviews_posted,reviews_last_edited,reviews_item_id,reviews_helpful,reviews_recommend,reviews_review
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,None,"Posted November 5, 2011.",None,1250,No ratings yet,True,Simple yet with great replayability. In my opi...
1,js41637,http://steamcommunity.com/id/js41637,None,"Posted June 24, 2014.",None,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...
2,evcentric,http://steamcommunity.com/id/evcentric,None,Posted February 3.,None,248820,No ratings yet,True,A suitably punishing roguelike platformer. Wi...
3,doctr,http://steamcommunity.com/id/doctr,None,"Posted October 14, 2013.",None,250320,2 of 2 people (100%) found this review helpful,True,This game... is so fun. The fight sequences ha...
4,maplemage,http://steamcommunity.com/id/maplemage,3 people found this review funny,"Posted April 15, 2014.",None,211420,35 of 43 people (81%) found this review helpful,True,Git gud

In [32]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59036 entries, 0 to 232129
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              59036 non-null  object
 1   user_url             59036 non-null  object
 2   reviews_funny        8132 non-null   object
 3   reviews_posted       59036 non-null  object
 4   reviews_last_edited  6083 non-null   object
 5   reviews_item_id      59036 non-null  object
 6   reviews_helpful      59036 non-null  object
 7   reviews_recommend    59036 non-null  bool
 8   reviews_review       59006 non-null  object
dtypes: bool(1), object(8)
memory usage: 4.1+ MB

In [33]:
#Elimino las columnas 'reviews_funny', 'reviews_last_edited' y 'user_url'
df_reviews = df_reviews.drop(columns=['reviews_funny', 'reviews_last_edited','user_url'])#faltan borrar columnas
df_reviews.columns

Index(['user_id', 'reviews_posted', 'reviews_item_id', 'reviews_helpful',
       'reviews_recommend', 'reviews_review'],
      dtype='object')

Cargo el dataset a la carpeta correspondiente

In [34]:
archivo_limpio = 'Datasets_limpio/user_reviews.csv'
df_reviews.to_csv(archivo_limpio, index=False, encoding='utf-8')

Aplicamos ETL a la data de items

In [35]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88310 entries, 0 to 88309
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      88310 non-null  object
 1   items_count  88310 non-null  int64
 2   steam_id     88310 non-null  object
 3   user_url     88310 non-null  object
 4   items        88310 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.4+ MB

In [36]:
df_items

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...,...,...,...
88305,76561198323066619,22,76561198323066619,http://steamcommunity.com/profiles/76561198323...,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
88306,76561198326700687,177,76561198326700687,http://steamcommunity.com/profiles/76561198326...,"[{'item_id': '11020', 'item_name': 'TrackMania..."
88307,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,[]
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"[{'item_id': '304930', 'item_name': 'Unturned'..."
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,[]

In [37]:
# se normaliza la columna 'items'
df_items_normal = pd.json_normalize(lista2, record_path=['items'], meta=['steam_id','items_count','user_id', 'user_url'] )
df_items_normal

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id,user_url
0,10,Counter-Strike,6,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,20,Team Fortress Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,30,Day of Defeat,7,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,40,Deathmatch Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
4,50,Half-Life: Opposing Force,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
...,...,...,...,...,...,...,...,...
5153204,346330,BrainBread 2,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153205,373330,All Is Dust,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153206,388490,One Way To Die: Steam Edition,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153207,521570,You Have 10 Seconds 2,4,4,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153208,519140,Minds Eyes,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...

In [38]:
#Observamos si hay duplicados
duplicados= df_items_normal.loc[df_items_normal.duplicated()]
duplicados

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id,user_url
164294,20,Team Fortress Classic,5,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164295,50,Half-Life: Opposing Force,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164296,70,Half-Life,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164297,130,Half-Life: Blue Shift,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164298,220,Half-Life 2,198,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
...,...,...,...,...,...,...,...,...
4898223,213670,South Park™: The Stick of Truth™,725,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898224,221910,The Stanley Parable,53,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898225,261030,The Walking Dead: Season Two,253,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898226,273110,Counter-Strike Nexon: Zombies,0,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898227,730,Counter-Strike: Global Offensive,0,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...

In [39]:
#Procedemos a borrar el total de duplicados (59104):
df_items_normal = df_items_normal.drop_duplicates(keep='first')
df_items_normal

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id,user_url
0,10,Counter-Strike,6,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,20,Team Fortress Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,30,Day of Defeat,7,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,40,Deathmatch Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
4,50,Half-Life: Opposing Force,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
...,...,...,...,...,...,...,...,...
5153204,346330,BrainBread 2,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153205,373330,All Is Dust,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153206,388490,One Way To Die: Steam Edition,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153207,521570,You Have 10 Seconds 2,4,4,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153208,519140,Minds Eyes,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...

In [40]:
#eliminamos las columnas innecesarias
df_items_normal = df_items_normal.drop(columns=['playtime_2weeks', 'user_url'], axis=1)
df_items_normal.columns

Index(['item_id', 'item_name', 'playtime_forever', 'steam_id', 'items_count',
       'user_id'],
      dtype='object')

In [41]:
#Exporto el ETL limpio a la carpeta correspondiente
archivo_limpio = 'Datasets_limpio/user_items.csv'
df_items_normal.to_csv(archivo_limpio, index=False, encoding='utf-8')